[package]
name = "ham-minon"
version = "0.1.0"
edition = "2024"

[dependencies]
dice-roll = { git = "https://github.com/hamologist/dice-roll.git", branch = "main", version = "0.1.0" }
poise = "0.6.1"
tokio = { version = "1.48.0", features = ["full"] }
